# Generated by Django 5.2.4 on 2025-07-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='')),
                ('cor', models.CharField(max_length=20)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
